server:
  port: 8088

spring:
  kafka:
    producer:
      bootstrap-servers: "[::1]:9092, [::1]:9094, [::1]:9096"
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: reporting-service
  data:
    redis:
      host: localhost
      port: 6379